<?php
/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2015  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */
?><?php if($this->permission->createAllowed()): ?>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

<form>
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Trainingszeit</label>
        <div class="col-sm-2">
            <select
                class="custom-select form-control form-control-sm"
                name="pdday"
                title="Wähle hier bitte den Tag aus."
            >
                <option value="1">Mo.</option>
                <option value="2">Di.</option>
                <option value="3">Mi.</option>
                <option value="4">Do.</option>
                <option value="5">Fr.</option>
                <option value="6">Sa.</option>
                <option value="0">So.</option>
            </select>
            <div class="valid-feedback"></div>
        </div>
        <div class="col-sm-2">
            <input
                class="form-control form-control-sm"
                type="time"
                name="pdfrom"
                value=""
                placeholder="Startuhrzeit"
                title="Gib hier bitte die Startzeit im Format hh::mm ein."
                maxlength="5"
            />
        </div>
        <div class="col-sm-2">
            <input
                name="pdtill"
                value=""
                class="form-control form-control-sm"
                type="time"
                placeholder="Enduhrzeit"
                title="Gib hier bitte die Endzeit im Vormat hh::mm ein."
                maxlength="5"
            />
        </div>
    </div>
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Beschreibung</label>
        <div class="col-sm-6">
            <input
                class="form-control form-control-sm"
                type="text"
                name="sddesc"
                value=""
                placeholder="Beschreibung"
                title="Gib hier bitte eine Beschreibung ein."
                maxlength="250"
            />
            <div class="valid-feedback"></div>
        </div>
    </div>
    <div class="modal-footer" style="border: 0; margin-top: 12px;">
        <button type="button" class="btn btn-success btn-sm submit-form">
            speichern
        </button>
        <button type="reset" class="btn btn-danger btn-sm">
            abbrechen
        </button>
    </div>
</form>
        </div>
        </div>
    </div>
<?php endif; ?>
<?php if(!count($this->periodicalDates) && !$this->permission->createAllowed()): ?>
<?php echo($this->showNoData());?>
<?php elseif(count($this->periodicalDates)): ?>
<table class="table table-sm table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col" colspan="5">Trainingszeiten</th>
            <th>

    <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">hinzufügen</button>
            </th>
        </tr>
    </thead>
    <tbody class="data nowrap">
        <?php foreach($this->periodicalDates as $v1): ?>
        <tr <?php if(empty($v1['from'])): ?>class="emptyrow"<?php endif; ?>>
            <td style="vertical-align: middle;"><?php echo($v1['day']);?></td>
            <?php if(empty($v1['from'])): ?>
            <td style="vertical-align: middle;" colspan="3">&nbsp;</td>
            <?php elseif($v1['till'] == ''): ?>
            <td style="vertical-align: middle;" colspan="3">
                ab <?php echo($v1['from']);?> Uhr
            </td>
            <?php else: ?>
            <td style="vertical-align: middle; text-align: right;"><?php echo($v1['from']);?></td>
            <td style="vertical-align: middle; text-align: center">-</td>
            <td style="vertical-align: middle;">
                <?php echo($v1['till']);?> Uhr
            </td>
            <?php endif; ?>
            <td style="vertical-align: middle; "><?php echo($v1['desc']);?></td>
            <?php if(($this->permission->deleteAllAllowed() || ($this->permission->deleteOwnAllowed() && $item['ownEntry'])) && !empty($v1['from'])): ?>
            <td style="vertical-align: middle; ">
                <button class="btn btn-danger btn-sm" value="" type="submit">löschen</button>
            </td>
            <?php else: ?>
            <td class="table-spacer"></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif;
